"""Tests for `jackpot.init.secrets` — secret-generation library + CLI."""

from __future__ import annotations

from pathlib import Path

import pytest
from click.testing import CliRunner
from jackpot_scenarios import get_scenario

from jackpot.cli.init import init
from jackpot.init.secrets import (
    SecretWriteRecord,
    assert_secret_path_invariant,
    generate_ed25519_keypair,
    generate_jwt_signing_key,
    populate_secrets,
    write_secret_file,
)

# ── Pure helpers ────────────────────────────────────────────────────────


class TestJwtSigningKey:
    def test_returns_64_char_hex(self):
        # 32-byte key → 64 hex chars.
        key = generate_jwt_signing_key()
        assert len(key) == 64
        assert all(c in "0123456789abcdef" for c in key)

    def test_each_call_unique(self):
        # Cryptographically secure source, so two adjacent calls MUST
        # differ. Birthday-collision probability vs 256 bits is ~0.
        keys = {generate_jwt_signing_key() for _ in range(50)}
        assert len(keys) == 50


class TestEd25519Keypair:
    def test_returns_pem_bytes(self):
        priv, pub = generate_ed25519_keypair()
        assert priv.startswith(b"-----BEGIN ED25519 PRIVATE KEY-----")
        assert priv.rstrip().endswith(b"-----END ED25519 PRIVATE KEY-----")
        assert pub.startswith(b"-----BEGIN ED25519 PUBLIC KEY-----")
        assert pub.rstrip().endswith(b"-----END ED25519 PUBLIC KEY-----")

    def test_private_and_public_differ(self):
        priv, pub = generate_ed25519_keypair()
        assert priv != pub

    def test_keypair_signs_and_verifies(self):
        # The PEM bytes contain the raw 32-byte key in hex between the
        # BEGIN/END lines. Round-trip through nacl to confirm the
        # generated bytes are a valid signing keypair.
        from nacl.encoding import RawEncoder
        from nacl.signing import SigningKey, VerifyKey

        priv_pem, pub_pem = generate_ed25519_keypair()
        priv_hex = priv_pem.split(b"\n")[1]
        pub_hex = pub_pem.split(b"\n")[1]
        priv_raw = bytes.fromhex(priv_hex.decode("ascii"))
        pub_raw = bytes.fromhex(pub_hex.decode("ascii"))

        sk = SigningKey(priv_raw, encoder=RawEncoder)
        vk = VerifyKey(pub_raw, encoder=RawEncoder)

        message = b"federation hello"
        signed = sk.sign(message)
        assert vk.verify(signed.message, signed.signature) == message


# ── write_secret_file ──────────────────────────────────────────────────


class TestWriteSecretFile:
    def test_writes_new_with_0600(self, tmp_path: Path):
        target = tmp_path / "secrets" / "jwt_signing_key.txt"
        rec = write_secret_file(
            target,
            "abcd",
            regenerate=False,
            confirm_overwrite=lambda _: False,
        )
        assert rec.action == "wrote_new"
        assert target.read_text() == "abcd"
        assert (target.stat().st_mode & 0o777) == 0o600

    def test_preserves_existing_without_regenerate(self, tmp_path: Path):
        target = tmp_path / "secrets" / "jwt_signing_key.txt"
        target.parent.mkdir(parents=True)
        target.write_text("ORIGINAL")
        rec = write_secret_file(
            target,
            "NEW",
            regenerate=False,
            confirm_overwrite=lambda _: True,  # would say yes, but flag is False
        )
        assert rec.action == "preserved"
        assert target.read_text() == "ORIGINAL"

    def test_overwrites_with_regenerate_and_confirm(self, tmp_path: Path):
        target = tmp_path / "secrets" / "jwt_signing_key.txt"
        target.parent.mkdir(parents=True)
        target.write_text("ORIGINAL")
        rec = write_secret_file(
            target,
            "NEW",
            regenerate=True,
            confirm_overwrite=lambda _: True,
        )
        assert rec.action == "regenerated"
        assert target.read_text() == "NEW"

    def test_preserves_when_regenerate_but_confirm_declined(self, tmp_path: Path):
        target = tmp_path / "secrets" / "jwt_signing_key.txt"
        target.parent.mkdir(parents=True)
        target.write_text("ORIGINAL")
        rec = write_secret_file(
            target,
            "NEW",
            regenerate=True,
            confirm_overwrite=lambda _: False,
        )
        assert rec.action == "preserved"
        assert target.read_text() == "ORIGINAL"


# ── populate_secrets — scenario-aware orchestration ────────────────────


class TestPopulateSecrets:
    def test_jwt_key_generated_for_every_scenario(self, tmp_path: Path):
        for code in ("A", "B", "C", "D", "E", "F", "T"):
            instance_dir = tmp_path / code
            populate_secrets(
                scenario=get_scenario(code),
                instance_dir=instance_dir,
                regenerate_secrets=False,
                confirm_overwrite=lambda _: True,
                oauth_secret_provider=lambda: None,
            )
            jwt_path = instance_dir / "secrets" / "jwt_signing_key.txt"
            assert jwt_path.exists(), code
            assert (jwt_path.stat().st_mode & 0o777) == 0o600
            assert len(jwt_path.read_text().strip()) == 64

    def test_federation_keypair_only_for_e_and_t(self, tmp_path: Path):
        for code in ("A", "B", "C", "D", "F"):
            instance_dir = tmp_path / code
            populate_secrets(
                scenario=get_scenario(code),
                instance_dir=instance_dir,
                regenerate_secrets=False,
                confirm_overwrite=lambda _: True,
                oauth_secret_provider=lambda: None,
            )
            assert not (instance_dir / "secrets" / "federation_private_key.pem").exists()
            assert not (instance_dir / "secrets" / "federation_public_key.pem").exists()

        for code in ("E", "T"):
            instance_dir = tmp_path / f"need_{code}"
            populate_secrets(
                scenario=get_scenario(code),
                instance_dir=instance_dir,
                regenerate_secrets=False,
                confirm_overwrite=lambda _: True,
                oauth_secret_provider=lambda: None,
            )
            assert (instance_dir / "secrets" / "federation_private_key.pem").exists()
            assert (instance_dir / "secrets" / "federation_public_key.pem").exists()

    def test_federation_private_key_0600_public_0644(self, tmp_path: Path):
        instance_dir = tmp_path / "fed"
        populate_secrets(
            scenario=get_scenario("E"),
            instance_dir=instance_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: None,
        )
        priv = instance_dir / "secrets" / "federation_private_key.pem"
        pub = instance_dir / "secrets" / "federation_public_key.pem"
        assert (priv.stat().st_mode & 0o777) == 0o600
        assert (pub.stat().st_mode & 0o777) == 0o644

    def test_oauth_secret_only_when_oauth_or_sso(self, tmp_path: Path):
        # F (mock) — no OAuth secret prompted.
        ci_dir = tmp_path / "ci"
        records = populate_secrets(
            scenario=get_scenario("F"),
            instance_dir=ci_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: pytest.fail("F should not prompt for OAuth"),
        )
        oauth_records = [r for r in records if "oauth" in r.path.name]
        assert all(r.action == "skipped_not_applicable" for r in oauth_records)

        # B (oauth) — provider called.
        provider_calls: list[None] = []

        def _provider() -> str:
            provider_calls.append(None)
            return "client-secret-from-google"

        b_dir = tmp_path / "b"
        records = populate_secrets(
            scenario=get_scenario("B"),
            instance_dir=b_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=_provider,
        )
        assert provider_calls
        secret_path = b_dir / "secrets" / "oauth_client_secret.txt"
        assert secret_path.exists()
        assert "client-secret-from-google" in secret_path.read_text()

    def test_oauth_secret_skipped_when_provider_returns_none(self, tmp_path: Path):
        b_dir = tmp_path / "b"
        records = populate_secrets(
            scenario=get_scenario("B"),
            instance_dir=b_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: None,
        )
        # File should NOT exist.
        assert not (b_dir / "secrets" / "oauth_client_secret.txt").exists()
        # Record action reflects skip.
        oauth_records = [r for r in records if "oauth" in r.path.name]
        assert any(r.action == "skipped_not_applicable" for r in oauth_records)

    def test_rerun_preserves_secrets_by_default(self, tmp_path: Path):
        instance_dir = tmp_path / "preserve"
        # First run.
        populate_secrets(
            scenario=get_scenario("E"),
            instance_dir=instance_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: "client-secret-1",
        )
        jwt_first = (instance_dir / "secrets" / "jwt_signing_key.txt").read_text()
        priv_first = (instance_dir / "secrets" / "federation_private_key.pem").read_bytes()

        # Second run, no regenerate.
        records = populate_secrets(
            scenario=get_scenario("E"),
            instance_dir=instance_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: "client-secret-2",
        )
        jwt_second = (instance_dir / "secrets" / "jwt_signing_key.txt").read_text()
        priv_second = (instance_dir / "secrets" / "federation_private_key.pem").read_bytes()

        assert jwt_first == jwt_second
        assert priv_first == priv_second
        assert all(r.action in ("preserved", "skipped_not_applicable") for r in records)

    def test_first_write_action_is_wrote_new_not_regenerated(self, tmp_path: Path):
        # Regression: the federation-keypair branch was using post-write
        # `.exists()` which is always True, mislabeling every first
        # write as "regenerated". Capture pre-write existence instead.
        instance_dir = tmp_path / "fresh"
        records = populate_secrets(
            scenario=get_scenario("E"),
            instance_dir=instance_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: None,
        )
        for rec in records:
            if rec.path.name in {
                "federation_private_key.pem",
                "federation_public_key.pem",
            }:
                assert rec.action == "wrote_new", (
                    f"first write should be wrote_new, got {rec.action!r} " f"for {rec.path.name}"
                )

    def test_second_write_with_regenerate_says_regenerated(self, tmp_path: Path):
        instance_dir = tmp_path / "rotate"
        # First run.
        populate_secrets(
            scenario=get_scenario("E"),
            instance_dir=instance_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: None,
        )
        # Second run with regenerate + confirm True.
        records = populate_secrets(
            scenario=get_scenario("E"),
            instance_dir=instance_dir,
            regenerate_secrets=True,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: None,
        )
        priv_record = next(r for r in records if r.path.name == "federation_private_key.pem")
        assert priv_record.action == "regenerated"

    def test_secrets_dir_is_0700(self, tmp_path: Path):
        instance_dir = tmp_path / "perms"
        populate_secrets(
            scenario=get_scenario("A"),
            instance_dir=instance_dir,
            regenerate_secrets=False,
            confirm_overwrite=lambda _: True,
            oauth_secret_provider=lambda: None,
        )
        secrets_dir = instance_dir / "secrets"
        assert (secrets_dir.stat().st_mode & 0o777) == 0o700


class TestSecretPathInvariant:
    def test_passes_when_all_paths_under_secrets(self, tmp_path: Path):
        records = [
            SecretWriteRecord(
                path=tmp_path / "secrets" / "jwt_signing_key.txt",
                action="wrote_new",
            ),
        ]
        assert_secret_path_invariant(records)  # no raise

    def test_raises_when_path_not_under_secrets(self, tmp_path: Path):
        records = [
            SecretWriteRecord(
                path=tmp_path / "stash" / "leak.txt",
                action="wrote_new",
            ),
        ]
        with pytest.raises(AssertionError, match="non-secret path"):
            assert_secret_path_invariant(records)

    def test_skipped_records_ignored(self, tmp_path: Path):
        # `skipped_not_applicable` paths can be anywhere; they're never written.
        records = [
            SecretWriteRecord(
                path=tmp_path / "anywhere.txt",
                action="skipped_not_applicable",
            ),
        ]
        assert_secret_path_invariant(records)  # no raise


# ── CLI integration ────────────────────────────────────────────────────


class TestSecretsCli:
    def _run_configure(self, runner: CliRunner, tmp_path: Path, scenario: str):
        return runner.invoke(
            init,
            [
                "configure",
                "--scenario",
                scenario,
                "--instance-name",
                f"test-{scenario.lower()}",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
                "--no-gh",
            ],
        )

    def test_secrets_requires_existing_instance(self, runner: CliRunner, tmp_path: Path):
        result = runner.invoke(
            init,
            [
                "secrets",
                "--instance",
                "nonexistent",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
            ],
        )
        assert result.exit_code != 0
        assert "does not exist" in result.output

    def test_secrets_after_configure_for_laptop(self, runner: CliRunner, tmp_path: Path):
        # Configure first.
        cfg = self._run_configure(runner, tmp_path, "A")
        assert cfg.exit_code == 0, cfg.output

        # Then secrets.
        result = runner.invoke(
            init,
            [
                "secrets",
                "--instance",
                "test-a",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
            ],
        )
        assert result.exit_code == 0, result.output
        jwt_path = tmp_path / "test-a" / "secrets" / "jwt_signing_key.txt"
        assert jwt_path.exists()
        # Federation skipped for A.
        assert "skipped_not_applicable" in result.output

    def test_secrets_for_federation_scenario_e(self, runner: CliRunner, tmp_path: Path):
        cfg = self._run_configure(runner, tmp_path, "E")
        assert cfg.exit_code == 0, cfg.output

        result = runner.invoke(
            init,
            [
                "secrets",
                "--instance",
                "test-e",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
            ],
        )
        assert result.exit_code == 0, result.output
        assert (tmp_path / "test-e" / "secrets" / "federation_private_key.pem").exists()
        assert (tmp_path / "test-e" / "secrets" / "federation_public_key.pem").exists()

    def test_secrets_for_tribal_t_generates_federation_keypair(
        self, runner: CliRunner, tmp_path: Path
    ):
        # Decision 5: T uses local keypair regardless of network policy.
        cfg = self._run_configure(runner, tmp_path, "T")
        assert cfg.exit_code == 0, cfg.output

        result = runner.invoke(
            init,
            [
                "secrets",
                "--instance",
                "test-t",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
            ],
        )
        assert result.exit_code == 0
        assert (tmp_path / "test-t" / "secrets" / "federation_private_key.pem").exists()

    def test_secrets_refuses_committed_ci_dir(self, runner: CliRunner, tmp_path: Path):
        # Configure a CI-local instance, then pretend the operator passed
        # --instance ci (the committed one).
        result = runner.invoke(
            init,
            [
                "configure",
                "--scenario",
                "F",
                "--instance-name",
                "ci-local",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
                "--no-gh",
            ],
        )
        assert result.exit_code == 0
        # Manually plant a jackpot.toml at instances/ci to simulate the
        # committed dir being present.
        ci_dir = tmp_path / "ci"
        ci_dir.mkdir()
        (ci_dir / "jackpot.toml").write_text(
            '[scenario]\ncode = "F"\nname = "CI / e2e test harness"\n'
        )

        result = runner.invoke(
            init,
            [
                "secrets",
                "--instance",
                "ci",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
            ],
        )
        assert result.exit_code != 0
        assert "Critical Rule 56" in result.output

    def test_regenerate_flag_with_non_interactive_preserves(
        self, runner: CliRunner, tmp_path: Path
    ):
        # First run — generate.
        self._run_configure(runner, tmp_path, "A")
        runner.invoke(
            init,
            [
                "secrets",
                "--instance",
                "test-a",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
            ],
        )
        jwt_path = tmp_path / "test-a" / "secrets" / "jwt_signing_key.txt"
        first = jwt_path.read_text()

        # Second run with --regenerate-secrets but --non-interactive
        # — confirm callback returns False, so secrets are PRESERVED.
        result = runner.invoke(
            init,
            [
                "secrets",
                "--instance",
                "test-a",
                "--instances-dir",
                str(tmp_path),
                "--non-interactive",
                "--regenerate-secrets",
            ],
        )
        assert result.exit_code == 0
        assert jwt_path.read_text() == first
        assert "preserved" in result.output
