"""
Pre-P0g Groovy nextflow.config generator (the "legacy" fallback path).

This module is the original hardcoded GCP-Batch config generator that
shipped before P0g introduced operator-configured execution profiles.
P0g G-4 keeps it in place as the fallback codepath when the resolution
chain in profile_resolver yields no profile (NoProfileAvailableError).
A future PR will retire this module once every deployment has at
least one execution profile.
"""

from __future__ import annotations

import re

from backend.config import get_settings

_LAB_SLUG_RE = re.compile(r"[^a-z0-9-]+")


def _slug(text: str) -> str:
    return _LAB_SLUG_RE.sub("-", text.lower()).strip("-") or "unknown"


def generate_run_config(
    *,
    run_id: str,
    pipeline_name: str,
    pipeline_version: str | None,
    lab_slug: str,
    pipeline_token: str,
    work_dir: str,
    result_uri: str,
) -> str:
    """
    Render the Groovy config passed to Nextflow via ``-c``.

    Includes resourceLabels for cost attribution (Critical Rule 27) and
    per-run workDir/result_uri so the run is fully isolated.
    """
    settings = get_settings()
    executor = getattr(settings, "pipeline_executor", "local")
    executor_flag = "google-batch" if executor == "gcp_batch" else executor
    api_url = getattr(settings, "jackpot_api_url", "http://localhost:8000")
    weblog_url = f"{api_url.rstrip('/')}/api/v1/pipelines/events"
    results_url = f"{api_url.rstrip('/')}/api/v1/pipelines/{run_id}/results"

    # Critical Rule 55: production code is operator-agnostic — no
    # operator-specific defaults (project IDs, region names, bucket
    # names) baked into source. The legacy GCP-Batch fallback path
    # requires an explicit gcp_project_id; loud failure at config
    # time beats silent fallback that surfaces as obscure GCP API
    # errors mid-run.
    project = settings.gcp_project_id
    if not project:
        raise RuntimeError(
            "gcp_project_id not configured. Set GCP_PROJECT_ID in env, "
            "or run `jackpot init` for guidance."
        )
    region = settings.gcp_region

    return f"""// Generated by JACKPOT POST /api/v1/pipelines/launch
// Run ID: {run_id} | Pipeline: {pipeline_name} {pipeline_version or ""}

process {{
    executor = "{executor_flag}"
    errorStrategy = 'retry'
    maxRetries = 2
}}

google {{
    project = "{project}"
    location = "{region}"
    batch.spot = true
    batch.bootDiskSize = 50.GB
    resourceLabels = [
        'jackpot_run_id': "{run_id}",
        'jackpot_lab':    "{_slug(lab_slug)}",
        'jackpot_pipeline': "{_slug(pipeline_name)}"
    ]
}}

workDir = "{work_dir}"

params {{
    jackpot_run_id      = "{run_id}"
    jackpot_api_url     = "{api_url}"
    jackpot_weblog_url  = "{weblog_url}"
    jackpot_results_url = "{results_url}"
    jackpot_result_uri  = "{result_uri}"
    jackpot_token       = "{pipeline_token}"
}}
"""
