apiVersion: v2
name: jackpot-api
description: JACKPOT FastAPI backend + Alembic migration Job.
type: application
version: 0.1.0
appVersion: "5.0.0"
home: https://github.com/Midnight-Oil-Innovation/jackpot
sources:
  - https://github.com/Midnight-Oil-Innovation/jackpot
maintainers:
  - name: Midnight-Oil-Innovation/jackpot maintainers
    url: https://github.com/Midnight-Oil-Innovation/jackpot
