apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jackpot-api.fullname" . }}-config
  labels:
    {{- include "jackpot-api.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $k, $v := .Values.buckets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
