"""
Detect-and-confirm hybrid for GitHub Actions repo variables.

Per design Decision 3: when `gh` is installed and authed, slurp the
existing repo vars from `gh api repos/$REPO/actions/variables` and
present each as `value found in GitHub: X — use this? [Y/n]`. Falls
through to typed-fresh prompts when `gh` is unavailable.

**Hard constraint:** secrets are NEVER slurped from GitHub. The
`gh api repos/X/actions/secrets` endpoint doesn't return values
anyway (only names), so this is enforced by GitHub's security model —
but be explicit in code that the only acceptable origins for secret
values are: (a) freshly generated by `jackpot init`, or (b) typed by
the operator at the prompt.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass


@dataclass(frozen=True)
class GhProbeResult:
    """Outcome of detecting whether `gh` is available + authed for a repo."""

    available: bool
    repo_slug: str | None  # "owner/repo" if detected, else None
    detail: str  # human-readable status (used in prompts + logs)


def probe_gh() -> GhProbeResult:
    """Detect whether the `gh` CLI is installed and authenticated.

    Returns a populated `GhProbeResult`. Never raises. Callers use
    `.available` to decide whether to slurp vars or fall through.
    """
    if shutil.which("gh") is None:
        return GhProbeResult(
            available=False,
            repo_slug=None,
            detail="gh CLI not found on PATH",
        )

    # `gh auth status` exits 0 only when authenticated. Capture the output
    # so a failure mode (rate-limited, expired token) ends up in `.detail`.
    try:
        result = subprocess.run(
            ["gh", "auth", "status"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
        return GhProbeResult(
            available=False,
            repo_slug=None,
            detail=f"gh probe failed: {exc}",
        )

    if result.returncode != 0:
        return GhProbeResult(
            available=False,
            repo_slug=None,
            detail=("gh CLI installed but not authenticated " "(`gh auth login` to fix)"),
        )

    # Try to detect the current repo from gh's view of the cwd.
    try:
        repo_result = subprocess.run(
            ["gh", "repo", "view", "--json", "nameWithOwner"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
        return GhProbeResult(
            available=True,
            repo_slug=None,
            detail=f"gh authed; repo detect failed ({exc})",
        )

    if repo_result.returncode != 0:
        return GhProbeResult(
            available=True,
            repo_slug=None,
            detail="gh authed; cwd is not a recognised GitHub repo",
        )

    try:
        repo_payload = json.loads(repo_result.stdout)
        repo_slug = repo_payload.get("nameWithOwner")
    except json.JSONDecodeError:
        repo_slug = None

    return GhProbeResult(
        available=True,
        repo_slug=repo_slug,
        detail=f"gh authed for repo {repo_slug}" if repo_slug else "gh authed",
    )


def fetch_repo_variables(repo_slug: str) -> dict[str, str]:
    """Fetch the GitHub Actions repo-level variables (NOT secrets).

    Returns name → value mapping. Empty dict on any error (absence is
    indistinguishable from "no vars set" — and either way the configure
    flow falls through to typed-fresh prompts).
    """
    try:
        result = subprocess.run(
            [
                "gh",
                "api",
                f"repos/{repo_slug}/actions/variables",
                "--paginate",
            ],
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {}

    if result.returncode != 0:
        return {}

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError:
        return {}

    # Response shape: {"total_count": N, "variables": [{"name": "X", "value": "Y"}, ...]}
    variables = payload.get("variables", [])
    return {v["name"]: v["value"] for v in variables if "name" in v and "value" in v}


def fetch_environment_variables(
    repo_slug: str,
    environment: str,
) -> dict[str, str]:
    """Fetch the GitHub Actions environment-scoped variables for a given env.

    Same shape as `fetch_repo_variables`. Empty dict on error.
    """
    try:
        result = subprocess.run(
            [
                "gh",
                "api",
                f"repos/{repo_slug}/environments/{environment}/variables",
                "--paginate",
            ],
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {}

    if result.returncode != 0:
        return {}

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError:
        return {}

    variables = payload.get("variables", [])
    return {v["name"]: v["value"] for v in variables if "name" in v and "value" in v}


__all__ = [
    "GhProbeResult",
    "fetch_environment_variables",
    "fetch_repo_variables",
    "probe_gh",
]
