"""
Post-bootstrap validation for `jackpot init validate`.

Per Decision 6 in the design doc: bootstrap orchestrates
`alembic upgrade head` → apply `seed.sql` → run validate. Validate
itself is a /health-loop smoke test — does the API answer, does the
response say `database: connected`, does the seeded admin row exist.

Pure-function library; the CLI in `cli/jackpot/cli/init.py` handles
flag parsing + Click output. Tests exercise the validators directly
without spinning up a real stack.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from pathlib import Path

import httpx


@dataclass(frozen=True)
class HealthCheckResult:
    ok: bool
    detail: str
    elapsed_seconds: float


def parse_api_url_from_env_local(env_local_path: Path) -> str:
    """Extract `JACKPOT_API_URL=...` from the per-instance .env.local.

    Falls back to `http://localhost:8000` when the file exists but the
    var isn't set (laptop / CI default). Raises FileNotFoundError when
    the file is missing — that's a misuse: bootstrap-before-configure.
    """
    if not env_local_path.exists():
        raise FileNotFoundError(
            f"{env_local_path} does not exist; run "
            f"`jackpot init configure --instance-name {env_local_path.parent.name}` first"
        )

    for line in env_local_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        if key.strip() == "JACKPOT_API_URL":
            cleaned = value.strip().strip('"').strip("'")
            return cleaned or "http://localhost:8000"
    return "http://localhost:8000"


def check_health(
    api_url: str,
    *,
    timeout_seconds: int = 60,
    poll_interval_seconds: float = 2.0,
    http_get=None,
    sleep=None,
    now=None,
) -> HealthCheckResult:
    """Poll `<api_url>/health` until it returns 200 with
    `database: connected`, or `timeout_seconds` elapses.

    `http_get`, `sleep`, `now` are injectable so tests can stub them.
    Defaults: httpx.get, time.sleep, time.monotonic.
    """
    _http_get = http_get or httpx.get
    _sleep = sleep or time.sleep
    _now = now or time.monotonic

    start = _now()
    last_detail = "no response yet"

    while True:
        elapsed = _now() - start
        if elapsed >= timeout_seconds:
            return HealthCheckResult(
                ok=False,
                detail=f"timed out after {elapsed:.1f}s — last status: {last_detail}",
                elapsed_seconds=elapsed,
            )

        try:
            response = _http_get(f"{api_url.rstrip('/')}/health", timeout=5.0)
        except Exception as exc:
            last_detail = f"connection failed: {exc}"
            _sleep(poll_interval_seconds)
            continue

        if response.status_code != 200:
            last_detail = f"HTTP {response.status_code}"
            _sleep(poll_interval_seconds)
            continue

        try:
            payload = response.json()
        except Exception as exc:
            last_detail = f"non-JSON body: {exc}"
            _sleep(poll_interval_seconds)
            continue

        if payload.get("status") == "ok" and payload.get("database") == "connected":
            return HealthCheckResult(
                ok=True,
                detail=(
                    f"healthy after {_now() - start:.1f}s "
                    f"(version={payload.get('version', '?')})"
                ),
                elapsed_seconds=_now() - start,
            )

        last_detail = f"status={payload.get('status')!r} " f"database={payload.get('database')!r}"
        _sleep(poll_interval_seconds)


@dataclass(frozen=True)
class BootstrapPreconditionResult:
    ok: bool
    missing: tuple[str, ...]


def check_bootstrap_preconditions(instance_dir: Path) -> BootstrapPreconditionResult:
    """Verify the files `jackpot init bootstrap` needs were generated by
    earlier subcommands (configure + secrets)."""
    required = (
        "jackpot.toml",
        ".env.local",
        "seed.sql",
        "secrets/jwt_signing_key.txt",
    )
    missing = tuple(rel for rel in required if not (instance_dir / rel).exists())
    return BootstrapPreconditionResult(ok=not missing, missing=missing)


__all__ = [
    "BootstrapPreconditionResult",
    "HealthCheckResult",
    "check_bootstrap_preconditions",
    "check_health",
    "parse_api_url_from_env_local",
]
