#!/usr/bin/env python3
"""scripts/gen_status.py — emit docs/STATUS.md from the live repo. Never hand-edit STATUS.md."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


def sh(cmd: str, default: str = "unknown") -> str:
    try:
        out = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=180)
        return (out.stdout or "").strip() or default
    except Exception:
        return default


def test_count() -> str:
    out = sh("uv run pytest --collect-only -q 2>/dev/null | tail -3", "")
    m = re.search(r"(\d+)\s+tests?\s+collected", out) or re.search(r"^(\d+)$", out, re.M)
    return m.group(1) if m else "unknown"


def alembic_head() -> str:
    versions = Path("backend/alembic/versions")
    if not versions.is_dir():
        return "unknown"
    revs, downs = {}, set()
    pat_r = re.compile(r"^revision(?:\s*:\s*[^=]+)?\s*=\s*['\"]([0-9a-fA-F]+)['\"]", re.M)
    pat_d = re.compile(r"^down_revision(?:\s*:\s*[^=]+)?\s*=\s*['\"]([0-9a-fA-F]+)['\"]", re.M)
    for f in versions.glob("*.py"):
        text = f.read_text(encoding="utf-8", errors="replace")
        if m := pat_r.search(text):
            revs[m.group(1)] = f.name
        if m := pat_d.search(text):
            downs.add(m.group(1))
    heads = [r for r in revs if r not in downs]
    return heads[0] if len(heads) == 1 else "FORKED"


def main() -> int:
    lines = [
        "# JACKPOT STATUS (generated by `make status` — do not hand-edit)",
        "<!-- status: reference -->",
        "",
        f"python_version: {sys.version_info.major}.{sys.version_info.minor}",
        "schema_version: v5.0",
        "scenario_count: 4",
        f"alembic_head: {alembic_head()}",
        f"test_count: {test_count()}",
        "",
    ]
    Path("docs").mkdir(exist_ok=True)
    Path("docs/STATUS.md").write_text("\n".join(lines) + "\n")
    print("wrote docs/STATUS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
